// CMatg class is defined in main.c
extern var CMath;

// this uses gravity std Math class
func stdmath() {
  var pi = Math.PI;
  var n1 = Math.log(pi);
	var n2 = Math.pow(pi, 2.12);
	return n1 + n2;
}

// this uses CMath class
func cmath() {
  var pi = CMath.pi;
  var n1 = CMath.log(pi);
	var n2 = CMath.pow(pi, 2.12);
	return n1 + n2;
}

// main function
func main() {
  System.print("\nGravity scripting language");
  System.print("--------------------------\n");

  System.print("Using  Math: " + stdmath());
  System.print("Using CMath: " + cmath());

  return 0;
}
